{"name": "test_login_2_fail_wrong[testdata1]", "status": "passed", "attachments": [{"name": "log", "source": "77a369ed-b9d3-4d91-948b-923dbe9658bb-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "testdata", "value": "{'user_name': '13760246701', 'user_pwd': 'pppp', 'msg': '帐号或密码错误!'}"}], "start": 1582978824978, "stop": 1582978825430, "uuid": "6036ab4e-32c1-4c9c-86ca-4410b5d2a3b9", "historyId": "7d57f15ad39fb6fe274d849185f9db61", "testCaseId": "36a98533581576596f44421c5526ef46", "fullName": "TestCases.test_login_new.TestLogin#test_login_2_fail_wrong", "labels": [{"name": "tag", "value": "test"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login_new"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Arlen"}, {"name": "thread", "value": "16884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_new"}]}